### ISSUE TITLE
Layer Label

### ISSUE THREAD

**Issue by thvi** [oodesign/arrange-artboards-hierarchically#4]
<img width="1280" alt="Screenshot 2019-04-20 at 10 08 30 AM" src="https://user-images.githubusercontent.com/6812634/56454656-874ec580-6354-11e9-921b-5b035d2c67d3.png">
The plugin does not work when the labels contain more than the prefix.
Bests,
Thierry

**Comment by oodesign** [comment]
Hi @thvi !

Sorry for the late reply :)

I can't see any hierarchy (based on the artboard names) in your design file. The only ones that do have the same root are the 2nd and 3rd ones (the ones with "A1/"), but they don't have any common parent (so... they're just "brothers", and displayed at the same level). The rest don't have any common root, so they're displayed at the same level.

If you want to create a hierarchy, you'd need something similar to this:

<img width="769" alt="Hierarchy" src="https://user-images.githubusercontent.com/11992834/56501832-88c4ed00-6510-11e9-8f40-59c5e203f4d6.png">

You may also find [here](https://www.dropbox.com/s/nhsopq76kamru64/Hierarchy.sketch?dl=0) a Sketch file with your original artboard list and a "Suggested" page with this one to see how it behaves.

Hope it helps!

**Comment by thvi** [comment]
Hello @oodesign!

Thanks 👍
